name: GFD280
channels:
  - conda-forge
dependencies:
  - python
  - scipy
  - matplotlib
  - ffmpeg
  - cartopy
  - dask
  - pandas
  - xarray
  - xgcm
  - netcdf4
  - zarr
  - cmocean
  - gsw
  - xhistogram
  - jupyterlab
  - wget
  - curl
  - pip
